# Generated by Django 5.2.4 on 2026-02-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0013_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
