# Generated by Django 5.2.4 on 2026-03-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0014_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Price',
        ),
        migrations.AddField(
            model_name='items',
            name='Brand',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='Engine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='Fixed_Price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='Gear_box',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='items',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='items',
            name='No_of_cylinder',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='items',
            name='On_Road_Price',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='Power',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='items',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=100),
        ),
    ]
