# Generated by Django 5.2.4 on 2026-03-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0015_remove_items_price_items_brand_items_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
