# Generated by Django 5.2.4 on 2026-03-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0016_alter_items_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTable',
        ),
    ]
