# Generated by Django 5.2.4 on 2026-03-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0017_delete_booktable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
