# Generated by Django 5.2.4 on 2026-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0019_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='items',
            name='Image5',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
